# Activer le support de la souris
CONFIG_ZMK_POINTING=y

# Activer les entrées analogiques (pour les joysticks)
CONFIG_ADC=y

# Améliorer la fluidité pour deux joysticks
# CONFIG_ZMK_MOUSE_SMOOTH_SCROLLING=y
